name: docker build and push

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: checkout cloudflred
        uses: actions/checkout@v4
        with:
          repository: cloudflare/cloudflared

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build image and push to docker hub
        run: |
          docker buildx build --push \
            --tag stroebs/cloudflared:latest  \
            --platform linux/arm/v7 .
